select  *
from    book;

DROP TABLE JSP_ADMIN.BOOK;

DROP SYNONYM BOOK;

SELECT  * FROM USER_USERS;

GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.BOOK TO JSP_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.MEMO TO JSP_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.MEMBER TO JSP_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.MEMBER_02 TO JSP_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.EMP2 TO JSP_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON JSP_ADMIN.MEMBER_03 TO JSP_DEV;

GRANT CREATE SYNONYM TO JSP_DEV;

  CREATE TABLE "JSP_ADMIN"."BOOK" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER DEFAULT 0, 
	"QTY" NUMBER DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JSP_DB"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JSP_DB" ;
 
CREATE TABLE MEMO (
IDX NUMBER NOT NULL PRIMARY KEY,
WRITER VARCHAR2(50) NOT NULL,
MEMO VARCHAR2(4000) NOT NULL,
POST_DATE DATE DEFAULT SYSDATE
);


CREATE TABLE MEMBER (
USERID VARCHAR2(50) NOT NULL PRIMARY KEY,
PASSWD VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE MEMBER_02 (
USER_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
PASSWD VARCHAR2(16) NOT NULL,
NAME VARCHAR2(10) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE,
ADDRESS VARCHAR2(500),
TEL VARCHAR2(50)
);

DROP TABLE EMP2;

select  *
from    user_tables;

select  *
from    emp;

CREATE TABLE EMP2 (
EMPNO VARCHAR2(10) PRIMARY KEY,
ENAME VARCHAR2(20) NOT NULL,
JOB VARCHAR2(20) NOT NULL,
MANAGER VARCHAR2(10),
HIREDATE DATE DEFAULT SYSDATE,
SAL VARCHAR(20),
COMM VARCHAR(20),
DEPTNO VARCHAR(20)
);

alter table emp2 drop constraint SYS_C0010969;



SELECT  *
FROM    MEMBER_02;


SELECT  *
FROM    MEMBER_03;


ALTER TABLE MEMBER_03 MODIFY PASSWD VARCHAR(64);

ALTER TABLE MEMBER_03 ADD (ZIPCODE VARCHAR2(7));

ALTER TABLE MEMBER_03 ADD (ADDRESS1 VARCHAR2(200));
ALTER TABLE MEMBER_03 ADD (ADDRESS2 VARCHAR2(200));
ALTER TABLE MEMBER_03 ADD (JOIN_DATE DATE DEFAULT SYSDATE);

ALTER TABLE MEMBER_03 DROP (REG_DATE);

INSERT INTO MEMBER_03 (USER_ID, PASSWD, NAME) VALUES ('kim', PACK_ENCRYPTION_DECRYPTION.FUNC_ENCRYPT('1234'), '±Ë∞˙¿Â');
INSERT INTO MEMBER_03 (USER_ID, PASSWD, NAME) VALUES ('park', PACK_ENCRYPTION_DECRYPTION.FUNC_ENCRYPT('1234'), '√÷∫Œ¿Â');
INSERT INTO MEMBER_03 (USER_ID, PASSWD, NAME) VALUES ('hong', PACK_ENCRYPTION_DECRYPTION.FUNC_ENCRYPT('1234'), '»´Ω«¿Â');

SELECT  *
FROM    MEMBER_03
WHERE   1=1
AND     USER_ID = 'kim'
AND     PASSWD = PACK_ENCRYPTION_DECRYPTION.FUNC_ENCRYPT('1234');

SELECT  USER_ID, PACK_ENCRYPTION_DECRYPTION.FUNC_DECRYPT(PASSWD)
FROM    MEMBER_03;


alter table member_03 add constraint user_id primary key (user_id);